on:
  workflow_call:  # Permite que este workflow seja chamado por outros workflows
    secrets:  # Permite receber os secrets
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  terraform-plan:
    name: "Terragrunt Plan"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: pip install awscli

      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Validar credenciais AWS
        run: aws sts get-caller-identity

      - name: Check if Terraform is a directory
        run: |
          if [ -d "/usr/local/bin/terraform" ]; then
            echo "Terraform is a directory. Removing..."
            sudo rm -rf /usr/local/bin/terraform
          fi 
      
      - name: Force remove old Terraform
        run: |
          sudo pkill -f terraform || true
          sudo rm -rf /usr/local/bin/terraform

      - name: Install Terraform
        run: |
          mkdir -p ~/terraform_install
          cd ~/terraform_install
          wget -q https://releases.hashicorp.com/terraform/1.10.5/terraform_1.10.5_linux_amd64.zip
          unzip -o terraform_1.10.5_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform --version

      - name: Install Terragrunt
        run: |
          wget https://github.com/gruntwork-io/terragrunt/releases/latest/download/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          terragrunt --version

      - name: Inicializar Terraform/Terragrunt
        working-directory: terraform
        run: terragrunt init

      - name: Executar Terraform Plan
        working-directory: terraform
        run: terragrunt plan -out=tfplan